
# ! Scene Information
eval_version: "re-implementation"
scene_category: "SINGLE_ROOM_SCENES"
scene_category: "MULTI_ROOM_SCENES"

scene: "i5noydFURQK"
scene_version: "0"

scene: "2t7WUuJeko7"
scene_version: "1"

scene: "i5noydFURQK"
scene_version: "0"

# scene: "Z6MFQCViBuw"
# scene_version: "0"

# scene: "PuKPg4mmafe"
# scene_version: "0"

# ! data Information
ly_model: 'hn_mp3d'
ly_scale: 1
vo_scale: 1
image_resolution: [512, 1024]

#! Plane  Estimation
plane_estimation.min_inliers_ratio: 0.80
plane_estimation.max_ransac_trials: 500
plane_estimation.min_ransac_residuals: 0.03
plane_estimation.ransac_prob_success: 0.999


# ! Plane Orientation Estimation
theta_estimation.min_explainability_ratio: 0.8
theta_estimation.initial_sigma: 360
theta_estimation.max_clearance: 30
theta_estimation.error_allowed: 1
theta_estimation.common_sigma: 30
theta_estimation.sigma_reduction: 1.01
theta_estimation.penalty: 0.5


# ! Room Identification
room_id.grid_size: 0.1
room_id.grid_padding: 50
room_id.ocg_threshold: 0.5
room_id.clipped_ratio: 5
room_id.iuo_overlapping_allowed: 0.3
room_id.non_isotropic_normalization: True
room_id.temporal_weighting: False


# ! Scale Recovering Parameters
scale_recover.max_vo_scale: 5
scale_recover.min_vo_scale: 0.01
scale_recover.sliding_windows: 10
scale_recover.initial_batch: 10
scale_recover.coarse_levels: 4
scale_recover.scale_step: 0.01
scale_recover.min_scale_variance: 0.01
scale_recover.grid_size: 0.1 
scale_recover.max_ocg_map_size: [1000, 1000] 
scale_recover.max_loops_iterations: 2
scale_recover.lys_for_warmup: 1
scale_recover.apply_gt_scale: True


room_shape_opt.valid_type: 'patch_boundary'
room_shape_opt.ocg_threshold: 0.7
room_shape_opt.spa_min_edge: 64
room_shape_opt.spa_max_edge: 64
room_shape_opt.grid_size_factor: 0.5
room_shape_opt.min_edge_dist: 0.0
# max_edge_dist: manhattan dist (pixel)
# if max_edge_dist=0, no max_edge_dist check will be used
room_shape_opt.max_edge_dist: 15
room_shape_opt.min_edge_angle_diff: 0.258 # 15 degree
room_shape_opt.sigma_corner: 1
room_shape_opt.sigma_plane: 1
room_shape_opt.average_plane_cost: False
room_shape_opt.use_angle_constraint: True
room_shape_opt.use_cross_product: False
room_shape_opt.use_constant_intersec: False
# weight_angle_diff: 100.0
room_shape_opt.weight_angle_diff: 2
room_shape_opt.weight_plane_cost: 10
room_shape_opt.weight_corner_cost: 0
room_shape_opt.weight_gop_closeness: 0
room_shape_opt.weight_gop_intersec: 100.0
room_shape_opt.weight_complex_cost: 10.0
room_shape_opt.merge_room_threshold: 0.5
room_shape_opt.merge_corner_threshold: 0.002

room_shape_opt.spa_refine_times: 2
room_shape_opt.refine_box_size: 4     # pixel
room_shape_opt.refine_sizes: [96, 96, 128, 128]
# refine_sizes: [108, 108, 144, 144]

# Evaluation options
evaluation.iou_threshold: 0.5
evaluation.dist_threshold: 10
evaluation.merge_corners: True    # corner metric
evaluation.merge_dist: 0.5        # meter